### ISSUE TITLE
JSON报错

### ISSUE THREAD

**Issue by lihaoyang991223** [yeximm/Access_wechat_article#2]
return _default_decoder.decode(s)
整体上没有问题，个别文章在爬评论时报错
经查似乎是单双引号的问题
PS：我不太会改，将报错的文章删除了

**Comment by lihaoyang991223** [comment]
新问题：当有文章被投诉不能显示时，会出现在文章列表里，但爬取评论时会报错退出。

**Comment by yeximm** [comment]
> return _default_decoder.decode(s) 整体上没有问题，个别文章在爬评论时报错 经查似乎是单双引号的问题 PS：我不太会改，将报错的文章删除了

先留一下文章链接吧，这段时间忙完了我看一下

**Comment by yeximm** [comment]
> 新问题：当有文章被投诉不能显示时，会出现在文章列表里，但爬取评论时会报错退出。

我还没遇到这种类型的，之前爬的都是各种官微，没有被投诉封掉的。

这个可以改动一下爬取文章的主程序，添加一个判断条件，如果抓取的文章是这种不能显示的，就返回一个标志交给后续程序判定。

**Comment by lihaoyang991223** [comment]
> > return _default_decoder.decode(s) 整体上没有问题，个别文章在爬评论时报错 经查似乎是单双引号的问题 PS：我不太会改，将报错的文章删除了
> 
> 先留一下文章链接吧，这段时间忙完了我看一下
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzA5NDMxMzQxMA==&scene=124#wechat_redirect
报错信息：
Traceback (most recent call last):
  File "E:\代码\微信公众号\Access_wechat_article-master\main.py", line 225, in <module>
    save_article_detail(biz.group(1), uin.group(1), key.group(1), pass_ticket.group(1))
  File "E:\代码\微信公众号\Access_wechat_article-master\main.py", line 148, in save_article_detail
    like_numss, detail_time, title, texts) = sad.get_detail_new(j, i)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\代码\微信公众号\Access_wechat_article-master\get_detail.py", line 73, in get_detail_new
    comments,like_nums=self.get_comment(comment_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\代码\微信公众号\Access_wechat_article-master\get_detail.py", line 90, in get_comment
    json_content = json.loads(response.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lihaoyang991223** [comment]
> > return _default_decoder.decode(s) 整体上没有问题，个别文章在爬评论时报错 经查似乎是单双引号的问题 PS：我不太会改，将报错的文章删除了
> 
> 先留一下文章链接吧，这段时间忙完了我看一下

同样的报错信息，差不多每400多篇就会出现一次，将爬过的文章从列表删除后，原来报错的文章又可以爬了，但还是每次只能爬400多篇，好像不是引号的问题，没搞明白

**Comment by yeximm** [comment]
> > > return _default_decoder.decode(s) 整体上没有问题，个别文章在爬评论时报错 经查似乎是单双引号的问题 PS：我不太会改，将报错的文章删除了
> > 
> > 
> > 先留一下文章链接吧，这段时间忙完了我看一下
> 
> 同样的报错信息，差不多每400多篇就会出现一次，将爬过的文章从列表删除后，原来报错的文章又可以爬了，但还是每次只能爬400多篇，好像不是引号的问题，没搞明白

行，忙完期末了再调整这个，也有可能是爬取速度太快了，你把延时函数弄的时间久一点再试试吧

**Comment by yeximm** [comment]
> > > return _default_decoder.decode(s) 整体上没有问题，个别文章在爬评论时报错 经查似乎是单双引号的问题 PS：我不太会改，将报错的文章删除了
> > 
> > 
> > 先留一下文章链接吧，这段时间忙完了我看一下
> 
> 同样的报错信息，差不多每400多篇就会出现一次，将爬过的文章从列表删除后，原来报错的文章又可以爬了，但还是每次只能爬400多篇，好像不是引号的问题，没搞明白

已更新，之前的问题试一下看看能不能解决
